### ISSUE TITLE
What version of VSCode is compatible?

### ISSUE THREAD

**Issue by sarobinsongit** [plasma-umass/scalene-vscode-extension#1]
Just tried to install to VSCode version:
Version: 1.79.1 (system setup)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:14:05.102Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
It is saying can not install because it is not compatible with this version of windows.
Any thoughts?

**Comment by emeryberger** [comment]
You need to use VS Code 1.82.0 or above (the latest version).

**Comment by sarobinsongit** [comment]
lol. I thought I had the latest code... but on reflection I reinstalled
recently from an install program I downloaded a few months ago
Guess it's time for a refresh.
Thanks for getting back to me.
Steve
