### ISSUE TITLE
Running scalene after VScode upgrade to the correct version

### ISSUE THREAD

**Issue by sarobinsongit** [plasma-umass/scalene-vscode-extension#2]
I upgrade vscode to the latest as you recommended. trying to run the program I get this:
Fatal error in launcher: Unable to create process using '"D:\bld\scalene_1694817879281\_h_env\python.exe"  "C:\ProgramData\miniconda3\scripts\scalene.exe" ': The system cannot find the file specified.
Should the path be updated with its location?
and before you ask see attached. :)
![Screenshot 2023-09-20 231701](https://github.com/plasma-umass/scalene-vscode-extension/assets/3993577/2a52378d-3eea-4d6a-b01c-0ba999dc8cfc)

**Comment by emeryberger** [comment]
I would think that if you've installed Scalene, the thing you need to do is to make sure you are using the same Python interpreter you used when you installed Scalene. The D:\bld\... thing seems pretty surprising.

**Comment by sarobinsongit** [comment]
I created a conda environment  and installed it there, works fine now.
thanks for your help
